version: "3.3"
services:
  qiyuan_db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: qiyuan_db
    restart: always
    environment:
      MYSQL_DATABASE: "qiyuan_db"
      MYSQL_USER: "alan"
      MYSQL_PASSWORD: "qiyuan_db"
      MYSQL_ROOT_PASSWORD: "qiyuan_db"
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - docker-db:/var/lib/mysql
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --init-connect='SET NAMES utf8mb4'
      --lower-case-table-names=1
      --skip-character-set-client-handshake

volumes:
  docker-db:
