version: "3.3"
services:
  qiyuan_db:
    image: mysql:5.7
    container_name: qiyuan_db
    restart: always
    environment:
      MYSQL_DATABASE: "qiyuan_db"
      MYSQL_USER: "alan"
      MYSQL_PASSWORD: "qiyuan_db"
      MYSQL_ROOT_PASSWORD: "qiyuan_db"
    ports:
      - 3308:3308
    expose:
      - "3308"
    volumes:
      - docker-db:/var/lib/mysql

volumes:
  docker-db:
